### ISSUE TITLE
Exception in the server log

### ISSUE THREAD

**Issue by mcCURS0R** [MineSworn/UltimateArena#149]
Task #16 for UltimateArena v2.7 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at net.dmulloy2.ultimatearena.arenas.Arena.announce(Arena.java:234) ~[?:?]
        at net.dmulloy2.ultimatearena.arenas.Arena.checkTimers(Arena.java:821) ~[?:?]
        at net.dmulloy2.ultimatearena.arenas.Arena.update(Arena.java:869) ~[?:?]
        at net.dmulloy2.ultimatearena.UltimateArena$ArenaUpdateTask.run(UltimateArena.java:1313)

**Comment by dmulloy2** [comment]
Use the latest development build of UltimateArena: http://ci.dmulloy2.net/job/UltimateArena/
