### ISSUE TITLE
Money Rewards not working in 1.7.10

### ISSUE THREAD

**Issue by draksterau** [MineSworn/UltimateArena#99]
Hi there,

I use Cauldron 1.7.10 w/ Forge 1236 and Vault 1.4.1 to hook into EssentialsEco.
For some reason Ultimate Arena fails to provide players with any monetary rewards using your money handling code. It does hand them item rewards.

Is it possible you can look into this, or you can explain how i can run a command on a player when they win( I can just do it that way using eco give I don't mind).

Arena Type used: PVP
Reward Based on XP (Tried on and Off)
Global Config for money rewards, true

UA Version: Latest as of today.

Regards,
Draksterau

**Comment by dmulloy2** [comment]
Try setting ````debug: true```` in the config and post any stack traces.  It sounds like the economy handling is failing silently.

**Comment by draksterau** [comment]
Several issues with chat similar to;

UltimateArena] [Debug] Encountered an exception while sending help to Bysokar: net.dmulloy2.ultimatearena.exception.ReflectionException: Constructing chat serializer
[20:53:11] [Server thread/INFO]: [UltimateArena] [Debug] Spawning player Bysokar in the lobby

It is worth noting I have the latest 1.7.10 hero chat installed.

Nothing mentioning players getting rewards other than "rewarding player Name" - doesn't say it is giving items but it does.

**Comment by draksterau** [comment]
Further testing, latest version of the mod appears to use cashReward: true, not moneyReward: true as in dock and previous config files.

But it still won't pay me!!! :(

**Comment by draksterau** [comment]
[08:04:14] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to UltimateArena v3.0-SNAPSHOT (Build 680)
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:382) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:547) [mw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:977) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) [mw.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:74) [GCEntityPlayerMP.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:196) [CraftLivingEntity.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.damage(CraftLivingEntity.java:181) [CraftLivingEntity.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:43) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:135) [Essentials.jar:?]
	at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:26) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:188) [Essentials.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:182) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:510) [Essentials.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:385) [Essentials.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1350) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1132) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.NullPointerException
	at net.dmulloy2.ultimatearena.listeners.EntityListener.onEntityDeath(EntityListener.java:317) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	... 32 more

**Comment by draksterau** [comment]
What version of Essentials do you support?

**Comment by dmulloy2** [comment]
I added some more log messages in the latest build.  When the plugin enables, if it recognizes your economy plugin, it'll log something along the lines of "Using [plugin] for economy."  It'll also log any exceptions encountered while attempting to deposit and send a message to the player.

**Comment by draksterau** [comment]
Thanks man! 

I'll try this after work today :D

**Comment by draksterau** [comment]
Hi @dmulloy2 I've tested with B682.

Unfortunately there's no new messages for economy handling in debug mode :(

**Comment by dmulloy2** [comment]
What is logged when the plugin is enabled?

**Comment by draksterau** [comment]
Yes mate, it's as if the code isn't called to prompt your debug message

Plugin is enabled.
